spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/OrderFlow/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/OrderFlow
        registration:
          keycloak:
            provider: keycloak
            client-id: gateway-security
            client-secret: hnIghZIpDVsewcowXZ0DmFX3IBcXSIBw
            authorization-grant-type: authorization_code
            scope: openid

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: product-get-route
              uri: lb://product-service
              predicates:
                - Path=/products
                - Method=GET
            - id: product-post-route
              uri: lb://product-service
              predicates:
                - Path=/products
                - Method=POST
              filters:
                - name: AuthFilter
                  args:
                    role: ROLE_USER

jwt:
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgu0xF3cXH932hP23DOm3UE0d79mqd6KKQcG8Irex6kkiuKKfKtse+mDjB6jrdjWIiCkzIEL6+mI70CbXKUQzidHXVy/EpHnokgtRaDzwnlI3cXwGaGA5j/n6rpsXJcg9wV+XBr9yMu6tajDecgtMthR0MNjHPLmwARuhw7IQ7g4w5ZNHAoYeaZIHtZf9HQY5sOO4Q2cu3q1gre97eENL3NMkZBTyg4fGCQDwQn5t8TxYJOZt8L2KqJLoWluJ1/SsEN2fzTiAhRQ8XCQfc8ZwuiYC9H49GVCp1GwMkFFLM4Oe86QYZRV8wkTETgo9LoU1lcgpzGMxs/4+NoFj8r3tzQIDAQAB
