spring:
  application:
    name: inventory-service
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5555/inventory-db}
    username: postgres
    password: 1234
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVER_1:localhost:29092}, ${KAFKA_SERVER_2:localhost:39092}

server:
  port: 8082
